version: "3.9"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  backend:
    image: "backend"
    ports:
      - "8081:8081"
    depends_on:
      - db

  frontend:
    image: "frontend"
    ports:
      - "80:80"