server:
  port: 8081
  servlet:
    context-path: /
jwt:
  secret: Mk_cMM4ER1PTQxzhCw8tpn5jhQq0gdvuRfCueEC7Jl8

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloud
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect